server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false
  datasource:
    host: ENC(ATGjyppUr6k+SwIV8DndS2ibC+KC92Ky)
    port: ENC(Fd3sl5IZh1ievGoXZq8B/Q==)
    dbName: ENC(2DlHJioLBSV8w/DMhag+QVwm4nzJZsYd)
    url: "jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.dbName}?createDatabaseIfNotExist=true"
    username: ENC(g+TFDbW46ph9Po+fg4BwzQ==)
    password: ENC(g+TFDbW46ph9Po+fg4BwzQ==)
    driver-class-name: "com.mysql.cj.jdbc.Driver"