server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
        format_sql: true
        show_sql: true
  datasource:
    host: ENC(l/zVDy/GrrwT0EsV4AJc9A==)
    port: ENC(Fd3sl5IZh1ievGoXZq8B/Q==)
    dbName: ENC(2DlHJioLBSV8w/DMhag+QVwm4nzJZsYd)
    url: "jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.dbName}?createDatabaseIfNotExist=true"
    username: ENC(g+TFDbW46ph9Po+fg4BwzQ==)
    password: ENC(g+TFDbW46ph9Po+fg4BwzQ==)
    driver-class-name: "com.mysql.cj.jdbc.Driver"
