server:
  port: 8081
spring:
  application:
    name: "pos-system"
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  output:
    ansi:
      enabled: always
  datasource:
    host: ENC(ATGjyppUr6k+SwIV8DndS2ibC+KC92Ky)
    port: ENC(s+rvumbiGAn1osS1NzJb4w==)
    dbName: ENC(2DlHJioLBSV8w/DMhag+QVwm4nzJZsYd)
    url: "jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.dbName}?createDatabaseIfNotExist=true"
    username: ENC(g+TFDbW46ph9Po+fg4BwzQ==)
    password: ENC(g+TFDbW46ph9Po+fg4BwzQ==)
    driver-class-name: "com.mysql.cj.jdbc.Driver"


jasypt:
  encryptor:
    password: Tech@1234
    bean: encryptorBean