server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
        format_sql: true
        show_sql: true
  datasource:
    url: "jdbc:mysql://localhost:13306/posSystem"
    username: root
    password: root
    driver-class-name: "com.mysql.cj.jdbc.Driver"